using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CVIServiceLibShared.Constants.Textos
{
    public  class Termos
    {
        public const string TERMOSDEUSO = "" +
            "Licença MIT\r\n\r\nDireitos autorais (c) 2021 MudBlazor\r\n\r\nA permissão é concedida, gratuitamente, a qualquer pessoa que obtenha uma cópia\r\ndeste software e arquivos de documentação associados (o \"Software\"), para lidar\r\nno Software sem restrições, incluindo, sem limitação, os direitos\r\nusar, copiar, modificar, fundir, publicar, distribuir, sublicenciar e/ou vender\r\ncópias do Software e para permitir que as pessoas a quem o Software é\r\nmunidos para o efeito, nas seguintes condições:\r\n\r\nO aviso de direitos autorais acima e este aviso de permissão devem ser incluídos em todos os\r\ncópias ou partes substanciais do Software.\r\n\r\nO SOFTWARE É FORNECIDO \"COMO ESTÁ\", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA OU\r\nIMPLÍCITAS, INCLUINDO, SEM LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO,\r\nADEQUAÇÃO PARA UM FIM ESPECÍFICO E NÃO VIOLAÇÃO. EM NENHUM CASO O\r\nOS AUTORES OU DETENTORES DOS DIREITOS AUTORAIS SERÃO RESPONSÁVEIS POR QUALQUER REIVINDICAÇÃO, DANOS OU OUTROS\r\nRESPONSABILIDADE, SEJA EM UMA AÇÃO DE CONTRATO, ILÍCITO OU DE OUTRA FORMA, DECORRENTE DE,\r\nFORA DE OU EM CONEXÃO COM O SOFTWARE OU O USO OU OUTROS NEGÓCIOS NO\r\nPROGRAMAS.";

        public const string TERMOLGPD = "TERMO DE ACEITE PARA TRATAMENTO DE DADOS PESSOAIS\r\nEste documento visa registrar a manifestação livre, informada e inequívoca pela qual o usuário concorda com o tratamento\r\nde seus dados pessoais para finalidade específica, em conformidade com a Lei nº 13.709 – Lei Geral de Proteção de\r\nDados Pessoais (LGPD).\r\nAo aceitar o presente termo, o usuário consente e concorda que a empresa VAGAS PRO \r\nEmpresariais de Santa Catarina, CNPJ nº 00.000.000/0000-00, com sede na Amazonas, 5550 – Bairro Centro\r\n– Votuporanga/SP, telefone (34)999674982  , e-mail pedro.emanoeltech@hotmail.com, doravante denominada Controlador, tome\r\ndecisões referentes ao tratamento de seus dados pessoais, bem como realize o tratamento de seus dados pessoais,\r\nenvolvendo operações como as que se referem a coleta, produção, recepção, classificação, utilização, acesso,\r\nreprodução, transmissão, distribuição, processamento, arquivamento, armazenamento, eliminação, avaliação ou controle\r\nda informação, modificação, comunicação, transferência, difusão ou extração.\r\nDados Pessoais\r\nO Controlador fica autorizado a tomar decisões referentes ao tratamento e a realizar o tratamento dos seguintes dados\r\npessoais do Titular:\r\n• Nome completo.\r\n• ACI que preside.\r\n• Número do Cadastro de Pessoas Físicas (CPF).\r\n• Endereço de e-mail pessoal\r\n• Regional da Facisc a qual a entidade que preside faz parte.\r\n• Validade do seu mandado\r\n• Seu voto em votações virtuais referente a itens estatutários.\r\nFinalidades do Tratamento dos Dados\r\nO tratamento dos dados pessoais listados neste termo tem as seguintes finalidades:\r\n• Possibilitar que o Controlador identifique e entre em contato com o Titular para fins de relacionamento.\r\n• Possibilitar que o Controlador possa dar acesso ao sistema de votação da VAGAS PRO\r\nCompartilhamento de Dados\r\nO Controlador fica autorizado a compartilhar os dados pessoais do Titular com outros agentes de tratamento de dados,\r\ncaso seja necessário para as finalidades listadas neste termo, observados os princípios e as garantias estabelecidas pela\r\nLei nº 13.709.\r\nSegurança dos Dados\r\nO Controlador responsabiliza-se pela manutenção de medidas de segurança, técnicas e administrativas aptas a proteger\r\nos dados pessoais de acessos não autorizados e de situações acidentais ou ilícitas de destruição, perda, alteração,\r\ncomunicação ou qualquer forma de tratamento inadequado ou ilícito.\r\nEm conformidade ao art. 48 da Lei nº 13.709, o Controlador comunicará ao Titular e à Autoridade Nacional de Proteção\r\nde Dados (ANPD) a ocorrência de incidente de segurança que possa acarretar risco ou dano relevante ao Titular.\r\nTérmino do Tratamento dos Dados\r\nO Controlador poderá manter e tratar os dados pessoais do Titular durante todo o período em que os mesmos forem\r\n";
    }
}
